papa: [
          "Gota",
          "Tizón Tardío",
          "Polilla Guatemalteca",
          "Marchitez Bacteriana",
        ],
        rosa: ["Mildeo", "Ácaros", "Trips", "Mancha Negra"],
        clavel: ["Fusarium", "Botritis", "Nemátodos", "Virus del Bronceado"],
        pompon: ["Oídio", "Mosca Blanca", "Minador de Hoja", "Royas"],
        crisantemo: ["Pythium", "Mancha Foliar", "Pulgones", "Tuta Absoluta"],
        hortensia: [
          "Clorosis",
          "Podredumbre Radicular",
          "Cochinillas",
          "Antracnosis",
        ],
        arroz: [
          "Pyricularia",
          "Helminthosporium",
          "Chinche del Arroz",
          "Malezas",
        ],
        tomate: ["Tuta Absoluta", "Mosca Blanca", "Virus del Mosaico", "Oídio"],
        cebolla: ["Trips", "Botritis", "Mildiu", "Podredumbre Blanca"],
        frijol: ["Antracnosis", "Mosca Blanca", "Roya", "Mustia Hilachosa"],
        fresa: ["Ácaro Ciclamen", "Botritis", "Oídio", "Mancha Angular"],
        aguacate: [
          "Trips",
          "Ácaro Cristalino",
          "Antracnosis",
          "Podredumbre Radicular",
        ],
        maiz: [
          "Gusano Cogollero",
          "Mancha de Asfalto",
          "Tizón Norteño",
          "Pulgones",
        ],
        arveja: ["Oídio", "Mildiu", "Trips", "Virus del Enanismo"],
      };